services:
  - type: web
    name: maa-durgakali-backend
    env: native
    plan: free
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/*.jar
    rootDir: backend
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false